name: 'Rails Migration Check'
description: 'Validate Rails migration files, run migrations automatically, and check schema.rb consistency'
author: 'Daigo Tanaka'

inputs:
  skip-migration-execution:
    description: 'Skip executing rails db:migrate (useful for testing or when migrations should not be run)'
    required: false
    default: 'false'
  migration-command:
    description: 'Custom migration command to run (default: bundle exec rails db:migrate)'
    required: false
    default: 'bundle exec rails db:migrate'
  working-directory:
    description: 'Working directory where the Rails project is located'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Set up environment
      shell: bash
      run: |
        echo "Setting up Rails Migration Check environment..."
        cd ${{ inputs.working-directory }}
        
    - name: Run migration check script
      shell: bash
      env:
        SKIP_MIGRATION_EXECUTION: ${{ inputs.skip-migration-execution }}
        MIGRATION_COMMAND: ${{ inputs.migration-command }}
      run: |
        cd ${{ inputs.working-directory }}
        ruby ${{ github.action_path }}/scripts/check_migrations.rb
        
branding:
  icon: 'check-circle'
  color: 'green'
